spring:
  profiles: default 


---

spring:
  application:
   name: bp-wallet-server
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:sampletest;MODE=MySQL

---

spring:
  profiles: dev
  application:
   name: bp-wallet-server
  datasource:
   url: jdbc:mysql://192.168.99.100:6603/sys?useSSL=false
   username: root
   password: mypassword
   driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
   hibernate.ddl-auto: update
   generate-ddl: false
   show-sql: false
   properties:
    hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect  
server:
  port: 0