server:
  port: 8080
spring:
  application:
    name: bp-wallet-client

grpc:
  client:
    bp-wallet-server:
      host:
        - 0.0.0.0
      port:
        - 9898
      enableKeepAlive: true
      keepAliveWithoutCalls: true